# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Test Repository Auditor
on:
  pull_request:
    paths:
      - 'edfi-repo-auditor/**'
  push:
    paths:
      - 'edfi-repo-auditor/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run unit, style, and type checks
    runs-on: ubuntu-latest
    defaults:
        shell: bash
        working-directory: edfi-repo-auditor
    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Install Poetry
        run: pipx install poetry

      - name: Install Python 3.9
        uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6 # v3.1.2
        with:
          python-version: "3.9"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install

      - name: Lint
        run: poetry run python flake8

      - name: Type Check
        run: poetry run mypy . --junit-xml mypy-junit.xml

      - name: Unit Tests
        run: poetry run pytest --junitxml=pytest-junit.xml

      - name: Upload PyTest Results
        uses: dorny/test-reporter@0d00bb14cb0cc2c9b8985df6e81dd333188224e1 #v1.5.0
        if: success() || failure()
        with:
            name: Pytest results
            path: "**/pytest-junit.xml"
            reporter: java-junit

      - name: Upload MyPy Results
        uses: dorny/test-reporter@0d00bb14cb0cc2c9b8985df6e81dd333188224e1 #v1.5.0
        if: success() || failure()
        with:
            name: MyPy results
            path: "**/mypy-junit.xml"
            reporter: java-junit
